In [1]:
#pip install clickhouse-driver

In [2]:
#pip install pandas

In [ ]:
DESCRIBE TABLE s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames');

DESCRIBE TABLE s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames') SETTINGS describe_compact_output=1

CREATE TABLE trips
(
    `trip_id` UInt32,
    `vendor_id` Enum8('1' = 1, '2' = 2, '3' = 3, '4' = 4, 'CMT' = 5, 'VTS' = 6, 'DDS' = 7, 'B02512' = 10, 'B02598' = 11, 'B02617' = 12, 'B02682' = 13, 'B02764' = 14, '' = 15),
    `pickup_date` Date,
    `pickup_datetime` DateTime,
    `dropoff_date` Date,
    `dropoff_datetime` DateTime,
    `store_and_fwd_flag` UInt8,
    `rate_code_id` UInt8,
    `pickup_longitude` Float64,
    `pickup_latitude` Float64,
    `dropoff_longitude` Float64,
    `dropoff_latitude` Float64,
    `passenger_count` UInt8,
    `trip_distance` Float64,
    `fare_amount` Float32,
    `extra` Float32,
    `mta_tax` Float32,
    `tip_amount` Float32,
    `tolls_amount` Float32,
    `ehail_fee` Float32,
    `improvement_surcharge` Float32,
    `total_amount` Float32,
    `payment_type` Enum8('UNK' = 0, 'CSH' = 1, 'CRE' = 2, 'NOC' = 3, 'DIS' = 4),
    `trip_type` UInt8,
    `pickup` FixedString(25),
    `dropoff` FixedString(25),
    `cab_type` Enum8('yellow' = 1, 'green' = 2, 'uber' = 3),
    `pickup_nyct2010_gid` Int8,
    `pickup_ctlabel` Float32,
    `pickup_borocode` Int8,
    `pickup_ct2010` String,
    `pickup_boroct2010` String,
    `pickup_cdeligibil` String,
    `pickup_ntacode` FixedString(4),
    `pickup_ntaname` String,
    `pickup_puma` UInt16,
    `dropoff_nyct2010_gid` UInt8,
    `dropoff_ctlabel` Float32,
    `dropoff_borocode` UInt8,
    `dropoff_ct2010` String,
    `dropoff_boroct2010` String,
    `dropoff_cdeligibil` String,
    `dropoff_ntacode` FixedString(4),
    `dropoff_ntaname` String,
    `dropoff_puma` UInt16
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(pickup_date)
ORDER BY pickup_datetime

SELECT *
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames')
LIMIT 10;

SELECT  _path, _file, trip_id
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_0.gz', 'TabSeparatedWithNames')
LIMIT 5;

SELECT count() AS count
FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames');

INSERT INTO trips
   SELECT *
   FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz', 'TabSeparatedWithNames')
   LIMIT 1000000;

In [3]:
from clickhouse_driver import Client
import pandas as pd

In [ ]:
client = Client(
    host='',
    user='default',
    password='',
    secure=True
)

In [5]:
print(client.execute('SELECT 1'))

[(1,)]

In [6]:
query = """
SELECT *
FROM helloworld.`trips`
LIMIT 10
"""

data = client.execute(query)

In [8]:
pd.DataFrame(data)

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,1202989588,1,2015-07-01,2015-07-01 00:00:03,2015-07-01,2015-07-01 00:14:37,0,1,0.000000,0.000000,...,0,0,0.0,0,,0000000,,0000,,0
1,1201746944,2,2015-07-01,2015-07-01 00:00:12,2015-07-01,2015-07-01 00:08:33,0,1,-73.978737,40.787659,...,3806,115,205.0,1,Manhattan,1020500,I,MN09,Morningside Heights,3802
2,1200864931,2,2015-07-01,2015-07-01 00:00:13,2015-07-01,2015-07-01 00:14:41,0,1,-73.990463,40.746117,...,3807,153,167.0,1,Manhattan,1016700,I,MN12,Upper West Side,3806
3,1202695666,2,2015-07-01,2015-07-01 00:00:13,2015-07-01,2015-07-01 00:15:01,0,1,-73.979568,40.759380,...,3807,13,37.0,1,Manhattan,1003700,I,MN24,SoHo-TriBeCa-Civic Center-Little Italy,3810
4,1200018648,2,2015-07-01,2015-07-01 00:00:16,2015-07-01,2015-07-01 00:02:57,0,1,-73.783585,40.648678,...,4105,8,716.0,4,Queens,4071600,I,QN98,Airport,4105
5,1201565885,1,2015-07-01,2015-07-01 00:00:16,2015-07-01,2015-07-01 00:20:09,0,1,-73.988106,40.764507,...,3807,0,9.0,1,Manhattan,1000900,I,MN25,Battery Park City-Lower Manhattan,3810
6,1201894280,2,2015-07-01,2015-07-01 00:00:19,2015-07-01,2015-07-01 00:20:23,0,1,-74.003258,40.731693,...,3810,0,138.0,1,Manhattan,1013800,I,MN32,Yorkville,3805
7,1201452450,2,2015-07-01,2015-07-01 00:00:20,2015-07-01,2015-07-01 00:11:07,0,1,-73.985794,40.727776,...,3809,78,77.0,1,Manhattan,1007700,I,MN23,West Village,3810
8,1200966844,2,2015-07-01,2015-07-01 00:00:21,2015-07-01,2015-07-01 00:08:01,0,1,-74.003799,40.747501,...,3807,52,48.0,1,Manhattan,1004800,I,MN21,Gramercy,3808
9,1201441307,2,2015-07-01,2015-07-01 00:00:21,2015-07-01,2015-07-01 00:20:11,0,1,-73.976067,40.750771,...,3808,8,230.0,1,Manhattan,1023000,E,MN03,Central Harlem North-Polo Grounds,3803

In [10]:
columns = [col[0] for col in client.execute(
    "DESCRIBE TABLE helloworld.`trips`"
)]

In [11]:

df = pd.DataFrame(data, columns=columns)
df.head()

,trip_id,vendor_id,pickup_date,pickup_datetime,dropoff_date,dropoff_datetime,store_and_fwd_flag,rate_code_id,pickup_longitude,pickup_latitude,...,pickup_puma,dropoff_nyct2010_gid,dropoff_ctlabel,dropoff_borocode,dropoff_ct2010,dropoff_boroct2010,dropoff_cdeligibil,dropoff_ntacode,dropoff_ntaname,dropoff_puma
0,1202989588,1,2015-07-01,2015-07-01 00:00:03,2015-07-01,2015-07-01 00:14:37,0,1,0.000000,0.000000,...,0,0,0.0,0,,0000000,,0000,,0
1,1201746944,2,2015-07-01,2015-07-01 00:00:12,2015-07-01,2015-07-01 00:08:33,0,1,-73.978737,40.787659,...,3806,115,205.0,1,Manhattan,1020500,I,MN09,Morningside Heights,3802
2,1200864931,2,2015-07-01,2015-07-01 00:00:13,2015-07-01,2015-07-01 00:14:41,0,1,-73.990463,40.746117,...,3807,153,167.0,1,Manhattan,1016700,I,MN12,Upper West Side,3806
3,1202695666,2,2015-07-01,2015-07-01 00:00:13,2015-07-01,2015-07-01 00:15:01,0,1,-73.979568,40.759380,...,3807,13,37.0,1,Manhattan,1003700,I,MN24,SoHo-TriBeCa-Civic Center-Little Italy,3810
4,1200018648,2,2015-07-01,2015-07-01 00:00:16,2015-07-01,2015-07-01 00:02:57,0,1,-73.783585,40.648678,...,4105,8,716.0,4,Queens,4071600,I,QN98,Airport,4105

In [13]:
metrics= {
    "total_trips": len(df),
    "total_revenue": df['fare_amount'].sum(),
    "avg_fare": df['fare_amount'].mean(),
    "avg_distance": df['trip_distance'].mean(),
    "avg_passengers": df['passenger_count'].mean()
}

In [14]:
metrics

{'total_trips': 10,
 'total_revenue': np.float64(126.5),
 'avg_fare': np.float64(12.65),
 'avg_distance': np.float64(3.257),
 'avg_passengers': np.float64(2.5)}

In [16]:
list(metrics.items())

[('total_trips', 10),
 ('total_revenue', np.float64(126.5)),
 ('avg_fare', np.float64(12.65)),
 ('avg_distance', np.float64(3.257)),
 ('avg_passengers', np.float64(2.5))]

In [17]:
metrics_df=pd.DataFrame(
    list(metrics.items()),
    columns=["metric_name","metric_value"]
)

In [18]:
metrics_df

      metric_name  metric_value
0     total_trips        10.000
1   total_revenue       126.500
2        avg_fare        12.650
3    avg_distance         3.257
4  avg_passengers         2.500

In [22]:
client.execute("""
CREATE TABLE IF NOT EXISTS helloworld.taxi_metrics
(
    metric_name String,
    metric_value Float64,
    created_at DateTime DEFAULT now()
)
ENGINE = MergeTree
ORDER BY metric_name
""")

[]

In [24]:
client.execute(
    "INSERT INTO helloworld.taxi_metrics (metric_name, metric_value) VALUES",
    metrics_df.to_dict("records")
)

5